export = {
    'DUPERSID': 'id',
    'TOTEXP12': 'spending_dist_total',
    'OPTEXP12': 'spending_dist_outpatient',
    'IPTEXP12': 'spending_dist_inpatient',
    'ERTEXP12': 'spending_dist_emergency',
    'OBTEXP12': 'spending_dist_office',
    'TOTMCD12': 'spending_pay_medicaid',
    'TOTMCR12': 'spending_pay_medicare',
    'TOTPRV12': 'spending_pay_private',
    'TOTSLF12': 'spending_pay_self',
    'FAMINC12': 'demo_fam_income',
    'POVLEV12': 'demo_fam_income_pl',
    'AGE12X': 'demo_age',
    'RACEV1X': 'demo_race_input',
    'RACEAX': 'demo_race_asian',
    'RACEBX': 'demo_race_black',
    'RACEWX': 'demo_race_white',
    'RACETHNX': 'demo_ethnicity_input',
    'EDUCYR': 'demo_education',
    'SEX': 'demo_sex',
    # 'ADGENH42': 'health_selfrate',
    # 'MNHLTH31': 'health_selfmental31',
    # 'MNHLTH42': 'health_selfmental42',
    # 'MNHLTH53': 'health_selfmental53',
    # 'PHQ242': 'health_feelings',
    'BMINDX53': 'health_bmi',
    'ADSMOK42': 'health_smoking',
    # 'IADLHP31': 'limits_IADL31',
    # 'IADLHP42': 'limits_IADL42',
    # 'IADLHP53': 'limits_IADL53',
    # 'IADL3M': 'limits_expectsIADL31',
    # 'IADL3M42': 'limits_expectsIADL42',
    # 'IADL3M53': 'limits_expectsIADL53',
    # 'WLKLIM31': 'limits_WLKLIM31',
    # 'WLKLIM53': 'limits_WLKLIM53',
    # 'WLK3MO31': 'limits_expectsWLKLIM31',
    # 'WLK3MO53': 'limits_expectsWLKLIM53',
    # 'UNABLE31': 'limits_unable31',
    # 'UNABLE53': 'limits_unable3153',
    'MCREV12': 'insurance_medicare',
    'MCDEV12': 'insurance_medicaid',
    'PRVEV12': 'insurance_private',
    'UNINS12': 'insurance_none',
    'HIBPDX': 'chronic_hbp',
    'BPMLDX': 'chronic_hbp2',
    'CHDDX': 'chronic_coronary',
    'MIDX': 'chronic_myocardial',
    'STRKDX': 'chronic_stroke',
    'DIABDX': 'chronic_diabetes',
    'ASTHDX': 'chronic_asthma',
    'ASATAK31': 'chronic_asthma_attack31',
    'ASATAK53': 'chronic_asthma_attack53',
    'ARTHDX': 'chronic_arthritis',
    'CANCERDX': 'chronic_cancer',
    'CABREAST': 'chronic_cancer_breast',
    'CACOLON': 'chronic_cancer_colon',
    'CALUNG': 'chronic_cancer_lung',
    'CAPROSTA': 'chronic_cancer_prostate',
    'CACERVIX': 'chronic_cancer_cervical',
    'IPDIS12': 'service_inpatient',
    # 'OPTOTV12': 'service_outpatient',
    # 'ERTOT12': 'service_emergency',
    # 'HHTOTD12': 'service_home',
    # 'RXTOT12': 'service_meds',
    'OBTOTV12': 'service_office',
    'HAVEUS42': 'gaps_USC_has42',
    # 'LOCATN42': 'gaps_USC_location',
    # 'YNOUSC42': 'gaps_USC_reason_main',
    # 'NOHINS42': 'gaps_USC_reason_uninsured',
    # 'USCNOT42': 'gaps_USC_reason_noavail',
    # 'CARECO42': 'gaps_USC_reason_cost',
    # 'MDUNAB42': 'gaps_care_unable',
    # 'MDUNPR42': 'gaps_care_problem',
    # 'MDUNRS42': 'gaps_care_reason',
    # 'PMUNAB42': 'gaps_meds_unable',
    # 'PMUNPR42': 'gaps_meds_problem',
    # 'PMUNRS42': 'gaps_meds_problem',
    # 'CHECK53': 'gaps_physical',
    # 'CHOLCK53': 'gaps_cholest',
    # 'BPCHECK': 'gaps_bp',
    # 'FLUSHT53': 'gaps_flu',
    # 'PSA53': 'gaps_prostate',
    # 'PAPSMR53': 'gaps_pap',
    # 'MAMMOGR': 'gaps_mamm',
    # 'BSTST53': 'gaps_stool',
    # 'CLNTST53': 'gaps_colon',
     'DSA1C53': 'diabetes_a1c',
     'DSFT1253': 'diabetes_foot',
     'DSE12y': 'diabetes_eye',
     'DSCH1253': 'diabetes_cholest'
}
